/**
 * Renders the query layer to markdown: one OVERVIEW.md for the repo and one
 * file per domain. Everything substantive comes from queries.ts — the same
 * answers the MCP server gives — so the two outputs can't disagree.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { GraphArtifact } from '../graph/schema.ts';
import {
  contextOf,
  domainDetail,
  overview,
  type Ctx,
  type DomainSummary,
  type OverviewData,
} from '../graph/queries.ts';

function pct(part: number, whole: number): string {
  if (whole === 0) return '—';
  return `${Math.round((part / whole) * 100)}%`;
}

function fnLabel(id: string): string {
  const hash = id.indexOf('#');
  return hash >= 0 ? `\`${id.slice(hash + 1)}\` (${id.slice('fn:'.length, hash)})` : `\`${id}\``;
}

function mermaidName(path: string): string {
  return path.replace(/[^a-zA-Z0-9]/g, '_');
}

function domainDiagram(summaries: DomainSummary[]): string {
  const lines = ['```mermaid', 'graph LR'];
  for (const s of summaries) lines.push(`  ${mermaidName(s.path)}["${s.name}"]`);
  for (const s of summaries) {
    for (const dep of s.dependsOn) {
      const label = dep.calls > 0 ? `${dep.calls} calls` : `${dep.imports} imports`;
      const arrow = dep.confirmed > 0 ? `==>|${label}|` : `-.->|${label}|`;
      lines.push(`  ${mermaidName(s.path)} ${arrow} ${mermaidName(dep.domain)}`);
    }
  }
  lines.push('```');
  return lines.join('\n');
}

export function renderOverview(data: OverviewData): string {
  const lines: string[] = [];
  lines.push(`# ${data.name} — architecture overview`);
  lines.push('');
  if (data.description) {
    lines.push(data.description, '');
  }
  lines.push(
    `${data.stats.files} files · ${data.stats.functions} functions · ${data.stats.loc} lines · ` +
      `${pct(data.stats.coveredFunctions, data.stats.functions)} of functions observed under test`,
    '',
  );

  lines.push('## Domains', '');
  lines.push('| domain | what it is | files | functions | observed |');
  lines.push('| --- | --- | ---: | ---: | ---: |');
  for (const d of data.domains) {
    const description = (d.description ?? '').replace(/\|/g, '\\|').slice(0, 140);
    lines.push(
      `| **${d.name}** | ${description} | ${d.files} | ${d.functions} | ${pct(d.coveredFunctions, d.functions)} |`,
    );
  }
  lines.push('');

  lines.push('## How the domains depend on each other', '');
  lines.push('Solid arrows were observed during a test run; dotted arrows are static analysis only.', '');
  lines.push(domainDiagram(data.domains), '');

  lines.push('## Suggested reading order', '');
  lines.push('Least-dependent domains first — each one only leans on what came before it.', '');
  data.readingOrder.forEach((path, i) => {
    const d = data.domains.find((s) => s.path === path);
    lines.push(`${i + 1}. **${path}**${d?.description ? ` — ${d.description.slice(0, 120)}` : ''}`);
  });
  lines.push('');

  if (data.entryPoints.length > 0) {
    lines.push('## Entry points', '');
    lines.push('Exported functions nothing inside the repo calls — where outside callers come in.', '');
    for (const e of data.entryPoints) {
      lines.push(`- ${fnLabel(e.id)}${e.summary ? ` — ${e.summary}` : ''}`);
    }
    lines.push('');
  }

  lines.push('## What this map cannot see', '');
  for (const l of data.limitations) lines.push(`- ${l}`);
  lines.push('');
  lines.push(
    `*Generated by gnosis — scanned ${data.scannedAt}${data.tracedAt ? `, traced ${data.tracedAt}` : ', not yet traced'}.*`,
  );
  return lines.join('\n') + '\n';
}

export function renderDomain(ctx: Ctx, path: string): string | undefined {
  const d = domainDetail(ctx, path);
  if (!d) return undefined;
  const lines: string[] = [];
  lines.push(`# ${d.name}`);
  lines.push('');
  if (d.description) lines.push(d.description, '');
  lines.push(
    `${d.files} files · ${d.functions} functions · ${d.loc} lines · ` +
      `${pct(d.coveredFunctions, d.functions)} observed under test`,
    '',
  );
  if (d.docPaths.length > 0) {
    lines.push(`Its own docs: ${d.docPaths.map((p) => `\`${p}\``).join(', ')}`, '');
  }

  if (d.dependsOn.length > 0 || d.dependedOnBy.length > 0) {
    lines.push('## Position in the architecture', '');
    for (const dep of d.dependsOn) {
      lines.push(`- calls into **${dep.domain}** (${dep.calls} call sites, ${dep.imports} imports${dep.confirmed ? `, ${dep.confirmed} observed` : ''})`);
    }
    for (const dep of d.dependedOnBy) {
      lines.push(`- called by **${dep.domain}** (${dep.calls} call sites, ${dep.imports} imports${dep.confirmed ? `, ${dep.confirmed} observed` : ''})`);
    }
    lines.push('');
  }

  if (d.topEdgesOut.length > 0) {
    lines.push('## Its most important outgoing calls', '');
    for (const e of d.topEdgesOut) {
      lines.push(`- ${fnLabel(e.from)} → ${fnLabel(e.to)}${e.confirmed ? ' *(observed)*' : ''}`);
    }
    lines.push('');
  }

  lines.push('## Files', '');
  lines.push('| file | lines | functions | observed | what it is |');
  lines.push('| --- | ---: | ---: | ---: | --- |');
  for (const f of d.fileRows) {
    if (f.testFile) continue;
    const summary = (f.summary ?? '').replace(/\|/g, '\\|').slice(0, 120);
    lines.push(`| \`${f.path}\` | ${f.loc} | ${f.functions} | ${f.functions ? pct(f.coveredFunctions, f.functions) : '—'} | ${summary} |`);
  }
  lines.push('');

  if (d.publicSurface.length > 0) {
    lines.push('## Public surface', '');
    for (const fn of d.publicSurface.slice(0, 60)) {
      lines.push(`- ${fnLabel(fn.id)}${fn.confirmed ? '' : ' *(unobserved)*'}${fn.summary ? ` — ${fn.summary}` : ''}`);
    }
    lines.push('');
  }

  if (d.mostCalled.length > 0) {
    lines.push('## Hottest functions under test', '');
    for (const fn of d.mostCalled) lines.push(`- ${fnLabel(fn.id)} — ${fn.calls} calls`);
    lines.push('');
  }
  if (d.untestedFiles.length > 0) {
    lines.push('## Files no test touches', '');
    for (const f of d.untestedFiles) lines.push(`- \`${f}\``);
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

export function emitMarkdown(graph: GraphArtifact, outDir: string): string[] {
  const ctx = contextOf(graph);
  const data = overview(ctx);
  mkdirSync(join(outDir, 'domains'), { recursive: true });
  const written: string[] = [];

  const overviewPath = join(outDir, 'OVERVIEW.md');
  writeFileSync(overviewPath, renderOverview(data));
  written.push(overviewPath);

  for (const d of data.domains) {
    const body = renderDomain(ctx, d.path);
    if (!body) continue;
    const path = join(outDir, 'domains', `${d.path.replace(/\//g, '-')}.md`);
    writeFileSync(path, body);
    written.push(path);
  }
  return written;
}
